### ISSUE TITLE
Infinite pagination

### ISSUE THREAD

**Issue by jayanthdeejay** [uclibs/scholar_uc#1781]
### Descriptive summary

While browsing works on scholar and while displaying scholar users, pagination has bugs. If there are 99 works and if we are displaying 10 works per page, ideally there should be 5 pages and on the 5th page, the "next" button should be disabled. 

next button is being disabled on the last page on top of all works as shown below

![screen shot 2017-12-04 at 2 35 18 pm](https://user-images.githubusercontent.com/2188493/33572306-8a6e7740-d900-11e7-8e53-3b671b7d604b.png)

but not at the bottom of all works

![screen shot 2017-12-04 at 2 35 28 pm](https://user-images.githubusercontent.com/2188493/33572325-99c67ee0-d900-11e7-8dc5-db2ce8f39c49.png)

If a user clicks next here, a blank page with no works opens up and a user can continue to click and looks like as follows

![screen shot 2017-12-04 at 2 38 14 pm](https://user-images.githubusercontent.com/2188493/33572397-d5f7ead4-d900-11e7-90fe-f739bf8f2c27.png)

### Expected behavior
To generate correct number of pages according to the number of works being displayed and next button on last page and previous button on first page should be disabled.

### Steps to reproduce the behavior

1. Go to scholar prod and browse works
1. Go to the last page of works and click next at the bottom of the page. It goes to the next page with empty works.

**Comment by jayanthdeejay** [comment]
https://github.com/samvera/hyrax/pull/1661/files

**Comment by scherztc** [comment]
Fixed in Hyrax 2.

**Comment by newmanld** [comment]
I'm re-opening this issue, so that we don't miss that this is a bug that we are expecting to be solved in Hyrax 2.x but is not yet solved in our current app.

**Comment by hortongn** [comment]
Resolved in Hyrax 2.x
